version: "3.9"

services:
  account:
    image: done/account:latest
    ports:
      - 5000:5000
    environment:
      - NODE_ENV=production
      - MONGO_SERVER_ADDR=mongo
      - MONGO_SERVER_PORT=27017
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: npm start
# Commented out: https://stackoverflow.com/a/49284315/659077
#    depends_on:
#      mongo:
#        condition: service_healthy
    networks:
      - traefik-public
    deploy:
      labels:
        - "traefik.enable=true"
        # Change the host url here
        - "traefik.http.routers.account-app.rule=Host(`account.example.ir`)"
        - "traefik.http.services.account-app.loadbalancer.server.port=5000"
        - "traefik.http.routers.account-app.middlewares=account-md"
#        - "traefik.http.routers.account-app.entrypoints=websecure"
        - "traefik.http.routers.account-app.entrypoints=web"
#        - "traefik.http.routers.account-app.tls=true"
#        - "traefik.http.routers.account-app.tls.certresolver=leresolver"
        # Change the password here
        - "traefik.http.middlewares.account-md.basicauth.users=admin:$$2y$$05$$XhiymfvW5iDUQBsAvOysfeonXELsfqyObi/E7X30A7/LCJHA.P1SG" # user/password

  mongo:
#    image: mongo:4.2.3-bionic
    image: mongo:7.0.2-jammy
#    ports:
#      - 27019:27017
    environment:
      - MONGO_INITDB_DATABASE=accountico
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASS}
#    volumes:
      # seeding scripts
#      - ./mongo-entrypoint:/docker-entrypoint-initdb.d
      # named volumes
#      - ./volumes/mongodb:/data/db
#      - ./mongoconfig:/data/configdb
    healthcheck:
      #test: ["CMD","mongosh", "--eval", "db.adminCommand('ping')"]
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s
    volumes:
      # seeding scripts
      - mongo_entrypoint:/docker-entrypoint-initdb.d
      # named volumes
      - mongo_data:/data/db
      - mongo_config:/data/configdb
    networks:
      - traefik-public

volumes:
  mongo_entrypoint:
  mongo_data:
  mongo_config:

networks:
  traefik-public:
    external: true
