version: "3"
services:
  account:
    ports:
      - 5000:5000
    environment:
      - NODE_ENV=production
      - MONGO_SERVER_ADDR=mongo
      - MONGO_SERVER_PORT=27017
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: npm start
    depends_on:
      mongo:
        condition: service_healthy

  mongo:
#    image: mongo:4.2.3-bionic
    image: mongo:7.0.2-jammy
#    ports:
#      - 27019:27017
    environment:
      - MONGO_INITDB_DATABASE=accountico
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASS}
    volumes:
      # seeding scripts
      - ./mongo-entrypoint:/docker-entrypoint-initdb.d
      # named volumes
      - ./volumes/mongodb:/data/db
      - ./mongoconfig:/data/configdb
    healthcheck:
      #test: ["CMD","mongosh", "--eval", "db.adminCommand('ping')"]
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s
